In [15]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [16]:
import torch

In [17]:
from learners.utils import get_cosine_distances, matching_logits, matching_loss, get_matching_accuracy

In [18]:
support_embeddings = torch.randn((1,5, 512))
support_targets = torch.randint(0,3,(1,5))
query_embeddings = torch.randn((1,2, 512))
query_targets = torch.randint(0,3,(1,2))

In [19]:
distances=get_cosine_distances(query_embeddings, support_embeddings)
distances

tensor([[[-0.0144, -0.0668],
         [ 0.0326,  0.0007],
         [ 0.0348,  0.0162],
         [-0.0387,  0.0478],
         [ 0.0047,  0.0157]]])

In [20]:
support_targets

tensor([[0, 2, 1, 1, 0]])

In [21]:
logits=matching_logits(distances, support_targets, num_classes=3)
logits

tensor([[[-0.0049, -0.0256],
         [-0.0019,  0.0320],
         [ 0.0326,  0.0007]]])

In [22]:
matching_loss(logits, query_targets)

tensor(1.1195)